#!/bin/bash

## Script to run the ERLConsole
##

EJC_CMD=`which "$0"`
while LINK=`readlink "$EJC_CMD"`; do EJC_CMD=$LINK; done
EJC_DIR=`dirname "$EJC_CMD"`

source $EJC_DIR/env_cfg

exec java -server -da \
    -Derj.threads=1 \
    -Xmx1g -Xss1m \
    -jar $EJC_DIR/erjang-0.1.jar \
    -home $HOME \
    -root $ERL_ROOT \
    +e $ERTS_VSN \
    $*
