#!/bin/bash

## Script to run the ERLConsole
##

EJ_CMD=`which "$0"`
while LINK=`readlink "$EJ_CMD"`; do EJ_CMD=$LINK; done
ERJANG_DIR=`dirname "$EJ_CMD"`

##    -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y \

exec java \
    -server \
    -Xmx1g -Xss50m \
    -XX:PermSize=128m \
    -jar $ERJANG_DIR/erjang-0.3.jar \
\
    -progname ej \
    +A 10 \
    +S 1 \
    "$@"
