#!/bin/bash

## Script to run the ERLConsole
##

EJC_CMD=`which "$0"`
while LINK=`readlink "$EJC_CMD"`; do EJC_CMD=$LINK; done
EJC_DIR=`dirname "$EJC_CMD"`

source $EJC_DIR/env_cfg

exec java \
    -server \
    -Xss1m \
    -Xmx2g \
    $OSX_DOCK_ICON \
    $OSX_DOCK_NAME \
    -cp $EJC_DIR/erjang-0.1.jar erjang.console.ERLConsole \
    -root "$ERL_ROOT" \
    +A 10 \
    +S 1 \
    +e "$ERTS_VSN" \
    -home "$HOME" \
    $*

