#!/bin/bash

## Script to run the ERLConsole
##

EJC_CMD=`which "$0"`
while LINK=`readlink "$EJC_CMD"`; do EJC_CMD=$LINK; done
ERJANG_DIR=`dirname "$EJC_CMD"`

source "$ERJANG_DIR/env_cfg"

###########################################################
# OS X - specific config
if [[ $(uname) == "Darwin" ]]; then
    OSX_DOCK_ICON="-Xdock:icon=$ERJANG_DIR/erjang_logo4.png"
    OSX_DOCK_NAME="-Xdock:name=ErjangConsole"
fi
###########################################################

# (TODO: OSX_DOCK variable expansions should expand into only one token - or zero, on non-OSX platforms.)
exec java \
    -server \
    -Xss1m \
    -Xmx2g \
    $OSX_DOCK_ICON \
    $OSX_DOCK_NAME \
    -Derjang.configfile="$PROP_FILE" \
    -Derjang.erts.version="$ERTS_VSN" \
    -Derjang.otp.version="$OTP_VSN" \
    -cp "$ERJANG_DIR/erjang-0.1.jar" erjang.console.ERLConsole \
\
    -root "$ERL_ROOT" \
    +A 10 \
    +S 1 \
    +e "$ERTS_VSN" \
    -home "$HOME" \
    "$@"
