#!/bin/bash

## Script to run the ERLConsole
##

EJ_CMD=`which "$0"`
while LINK=`readlink "$EJ_CMD"`; do EJ_CMD=$LINK; done
ERJANG_DIR=`dirname "$EJ_CMD"`

exec java \
    -server \
    -Djava.library.path=$ERJANG_DIR/jnif \
    -Xmx1g -Xss50m \
    -jar $ERJANG_DIR/erjang-0.2.jar \
\
    -progname $EJ_CMD \
    "$@"
