/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class erjang_NIF */

#ifndef _Included_erjang_NIF
#define _Included_erjang_NIF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     erjang_NIF
 * Method:    jni_invoke
 * Signature: (JI[Lerjang/EObject;)Lerjang/EObject;
 */
JNIEXPORT jobject JNICALL Java_erjang_NIF_jni_1invoke
  (JNIEnv *, jobject, jlong, jint, jobjectArray);

/*
 * Class:     erjang_NIF
 * Method:    jni_load
 * Signature: (Ljava/lang/String;Lerjang/EObject;)J
 */
JNIEXPORT jlong JNICALL Java_erjang_NIF_jni_1load
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
