/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class erjang_EResource */

#ifndef _Included_erjang_EResource
#define _Included_erjang_EResource
#ifdef __cplusplus
extern "C" {
#endif
#undef erjang_EResource_CMP_ORDER_ERJANG_INTERNAL
#define erjang_EResource_CMP_ORDER_ERJANG_INTERNAL -1L
#undef erjang_EResource_CMP_ORDER_NUMBER
#define erjang_EResource_CMP_ORDER_NUMBER 0L
#undef erjang_EResource_CMP_ORDER_ATOM
#define erjang_EResource_CMP_ORDER_ATOM 1L
#undef erjang_EResource_CMP_ORDER_REFERENCE
#define erjang_EResource_CMP_ORDER_REFERENCE 2L
#undef erjang_EResource_CMP_ORDER_FUN
#define erjang_EResource_CMP_ORDER_FUN 3L
#undef erjang_EResource_CMP_ORDER_PORT
#define erjang_EResource_CMP_ORDER_PORT 4L
#undef erjang_EResource_CMP_ORDER_PID
#define erjang_EResource_CMP_ORDER_PID 5L
#undef erjang_EResource_CMP_ORDER_TUPLE
#define erjang_EResource_CMP_ORDER_TUPLE 6L
#undef erjang_EResource_CMP_ORDER_LIST
#define erjang_EResource_CMP_ORDER_LIST 7L
#undef erjang_EResource_CMP_ORDER_BITSTRING
#define erjang_EResource_CMP_ORDER_BITSTRING 8L
/*
 * Class:     erjang_EResource
 * Method:    jni_finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_erjang_EResource_jni_1finalize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
